export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const TOGGLE_LEFT_MENU = 'TOGGLE_LEFT_MENU';
export const TOGGLE_MAIN_MENU = 'TOGGLE_MAIN_MENU';
export const CHANGE_EXPERT_ACTIVE_TAB = 'CHANGE_EXPERT_ACTIVE_TAB';
